import { useEffect, useState } from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from "./index.module.css"
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Divider from '@mui/material/Divider'
import Typography from '@mui/material/Typography'

import PiMonteCarlo from '@/components/modules/PiMonteCarlo';
import LinearRegression from '@/components/modules/LinearRegression';
import Triangle from '@/components/modules/Triangle';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Paper elevation={1} className={styles.leftContainer}>
          <PiMonteCarlo width={500} height={500} maxSamples={2000} onChange={() => {}}/>
        </Paper>
        <Divider/>
        <Paper elevation={1} className={styles.rightContainer}>
          <LinearRegression width={500} height={500}/>
        </Paper>
        <Divider/>
        <Paper elevation={1} className={styles.leftContainer}>
          <Triangle width={500} height={500} onChange={console.log}/>
        </Paper>
      </Box>
    </>
  )
}
